export type Locale = 'zh-CN' | 'en' | 'ru' | 'ja';

export const SUPPORTED_LOCALES: readonly Locale[] = ['zh-CN', 'en', 'ru', 'ja'];

const messages: Record<Locale, Record<string, string>> = {
  'zh-CN': {
    'language.label': '语言', 'language.zh-CN': '简体中文', 'language.en': 'English', 'language.ru': 'Русский', 'language.ja': '日本語',
    'brand.account': '用户中心', 'brand.back': '返回论坛', 'brand.powered': 'MindAuth 为 MDTBBS 及关联社区应用提供统一账号服务。',
    'brand.tagline': 'Mindustry 中文玩家社区', 'brand.description': '寻找 Mod、地图、蓝图与讨论。', 'brand.visit': '访问 MDTBBS',
    'auth.continue': '登录后继续访问 {client}', 'auth.directDescription': '使用 MindAuth 账号访问社区与关联服务。', 'auth.login': '登录',
    'auth.register': '注册', 'auth.noAccount': '没有账号？', 'auth.haveAccount': '已有账号？', 'auth.forgot': '忘记密码', 'auth.usernameOrEmail': '用户名或邮箱',
    'auth.password': '密码', 'auth.usernamePlaceholder': '请输入用户名或邮箱', 'auth.passwordPlaceholder': '请输入密码',
    'auth.loginError': '登录失败', 'auth.connecting': '正在连接应用：{client}', 'auth.chooseLogin': '选择登录方式',
    'auth.passwordTab': '账号密码', 'auth.qq': 'QQ 登录', 'auth.qqDescription': '使用已绑定的 QQ 账号登录 MDTBBS。', 'auth.loginWithQQ': '使用 QQ 登录',
    'auth.loginSuccess': '登录成功', 'auth.loginFailed': '登录失败', 'auth.enterCredentials': '请输入用户名/邮箱和密码',
    'oauth.title': '确认应用授权', 'oauth.description': '请确认应用的身份和它申请的权限。',
    'error.emailVerification': '请先验证邮箱，再创建开发者应用。', 'error.phoneVerification': 'MDTBBS 生态的开发者应用需要验证手机号。',
    'nav.dashboard': '概览', 'nav.account': '账户', 'nav.profile': '个人资料', 'nav.security': '安全', 'nav.sessions': '登录设备', 'nav.activity': '登录记录', 'nav.apps': '应用', 'nav.authorizations': '授权应用', 'nav.messages': '消息', 'nav.notifications': '通知', 'nav.developer': '开发', 'nav.developerApps': '应用管理',
    'nav.securityGroup': '安全', 'nav.messagesGroup': '消息',
    'legal.terms': '用户协议', 'legal.privacy': '隐私政策', 'legal.about': '关于与声明', 'legal.aria': '法律与站点信息',
    'profile.title': '个人资料', 'profile.description': '管理头像、横幅、用户名和展示资料。', 'profile.avatar': '头像', 'profile.avatarDescription': '使用清晰的图片帮助识别你的账户。', 'profile.avatarTitle': '账户头像', 'profile.imageTypes': '支持 JPEG、PNG、GIF 或 WebP，最大 {size}MB。', 'profile.changeAvatar': '更换头像', 'profile.remove': '移除', 'profile.basic': '基本资料', 'profile.basicDescription': '用于展示和识别你的 MindAuth 账户。', 'profile.username': '用户名', 'profile.usernameDescription': '每 30 天可更改一次；更改后需要重新登录。', 'profile.usernameHint': '2–50 个字符，支持字母、数字、下划线、连字符和中文', 'profile.saveUsername': '保存用户名', 'profile.email': '邮箱', 'profile.emailDescription': '邮箱用于登录和账户恢复，修改操作位于安全设置。', 'profile.verified': '已验证', 'profile.pending': '待验证', 'profile.verifyEmail': '验证邮箱', 'profile.createdAt': '账户创建时间', 'profile.banner': '个人横幅', 'profile.bannerDescription': '横幅用于个人资料展示，不会出现在账户概览中。', 'profile.bannerTitle': '横幅图片', 'profile.bannerTypes': '支持 JPEG、PNG、GIF 或 WebP，最大 5MB。', 'profile.bannerPreview': '个人横幅预览', 'profile.bannerUnset': '尚未设置横幅', 'profile.changeBanner': '更换横幅', 'profile.custom': '自定义资料', 'profile.customDescription': '填写由 MindAuth 管理员提供的可选资料字段。', 'profile.choose': '请选择', 'profile.required': '必填', 'profile.optional': '选填', 'profile.save': '保存资料', 'profile.emptyFields': '目前没有可编辑的自定义字段。', 'profile.newUsernameRequired': '请输入新的用户名。', 'profile.usernameUpdated': '用户名已更新，请重新登录。', 'profile.usernameFailed': '修改用户名失败。', 'profile.fieldsSaved': '自定义资料已保存。', 'profile.fieldsSaveFailed': '保存资料失败。', 'profile.imageTooLarge': '图片大小不能超过 {size}MB。', 'profile.avatarUpdated': '头像已更新。', 'profile.bannerUpdated': '横幅已更新。', 'profile.uploadFailed': '上传失败。', 'profile.avatarDeleted': '头像已删除。', 'profile.bannerDeleted': '横幅已删除。', 'profile.deleteFailed': '删除失败。',
    'shared.loading': '加载中', 'shared.loadFailed': '加载失败，请检查连接后重试。', 'shared.retry': '重试',
    'activity.title': '登录记录', 'activity.description': '查看 MindAuth 记录的近期账户登录活动。', 'activity.recent': '近期登录', 'activity.details': '记录包含登录时间、客户端、IP 地址和登录方式；不提供地理位置或失败状态。', 'activity.time': '时间', 'activity.client': '客户端', 'activity.ip': 'IP 地址', 'activity.method': '登录方式', 'activity.notProvided': '未提供', 'activity.empty': '没有登录记录。', 'activity.web': 'Web 登录', 'activity.oauth': 'OAuth 登录', 'activity.native': '客户端登录', 'activity.social': '关联账号登录', 'activity.generic': '登录',
    'authorization.title': '授权应用', 'authorization.description': '查看通过 MindAuth 接入账户的应用及其获得的权限。', 'authorization.current': '当前授权', 'authorization.currentDescription': '撤销授权会同时使该应用的相关令牌失效。', 'authorization.public': '公开客户端', 'authorization.confidential': '机密客户端', 'authorization.thirdParty': '第三方应用', 'authorization.firstParty': '第一方应用', 'authorization.revoke': '撤销授权', 'authorization.created': '授权时间', 'authorization.lastUsed': '最近使用', 'authorization.noRecentUse': '暂无记录', 'authorization.scope': '权限范围', 'authorization.noScope': '未提供权限范围', 'authorization.empty': '没有已授权的应用。', 'authorization.revokeTitle': '撤销应用授权', 'authorization.cancel': '取消', 'authorization.confirm': '确认撤销', 'authorization.revokeBody': '撤销 {client} 的授权后，该应用将无法继续访问此账户，相关令牌也会失效。', 'authorization.revoked': '已撤销 {client} 的授权。', 'authorization.failed': '撤销授权失败。',
    'notification.title': '通知', 'notification.description': '查看 MindAuth 的账户、安全和服务消息。', 'notification.center': '通知中心', 'notification.count': '共 {count} 条通知', 'notification.latest': '最新的账户消息会显示在这里。', 'notification.markAll': '全部标记已读', 'notification.unread': '未读', 'notification.markRead': '标记已读', 'notification.delete': '删除', 'notification.empty': '暂无需要处理的通知。', 'notification.pageLabel': '通知分页', 'notification.previous': '上一页', 'notification.next': '下一页', 'notification.page': '第 {page} / {total} 页', 'notification.readAllSuccess': '所有通知已标记为已读。', 'notification.readAllFailed': '标记通知失败。', 'notification.deleteFailed': '删除通知失败。',
    'session.title': '登录设备', 'session.description': '查看近期使用过此账户的浏览器和客户端，并结束不再使用的会话。', 'session.current': '当前设备', 'session.currentDescription': '当前设备会话仅在你明确选择退出时结束。', 'session.others': '其他设备', 'session.othersDescription': '退出陌生或不再使用的设备，会立即撤销对应会话。', 'session.revokeAll': '退出其他所有设备', 'session.noCurrent': '当前浏览器没有可识别的活动会话。', 'session.noOthers': '没有其他登录设备。', 'session.confirmAll': '退出其他所有设备', 'session.confirmDevice': '确认退出设备', 'session.cancel': '取消', 'session.confirm': '确认退出', 'session.bodyAll': '将退出 {count} 台其他设备。当前设备会保持登录。', 'session.bodyCurrent': '这会退出当前设备并结束本次 MindAuth 登录。', 'session.bodyOther': '退出后，该设备需要重新登录才能继续使用 MindAuth。', 'session.currentLabel': '当前设备', 'session.native': '客户端', 'session.browser': 'Web 浏览器', 'session.ipMissing': 'IP 未提供', 'session.recentActivity': '最近活动', 'session.loginTime': '登录时间', 'session.signOutCurrent': '退出当前设备', 'session.signOut': '退出此设备', 'session.signedOut': '设备已退出。', 'session.currentSignedOut': '当前设备已退出。', 'session.otherSignedOut': '其他设备已全部退出。', 'session.partialFailure': '已退出 {success} 台设备，{failed} 台设备退出失败。', 'session.revokeFailed': '退出设备失败。',
    'dashboard.title': '账户', 'dashboard.description': '查看身份状态、安全设置、登录设备和应用授权。', 'dashboard.identity': '账户身份', 'dashboard.status': '账户状态', 'dashboard.emailVerified': '邮箱已验证', 'dashboard.emailPending': '邮箱待验证', 'dashboard.phoneBound': '手机号已绑定', 'dashboard.phoneOptional': '手机号（可选）', 'dashboard.profile': '个人资料', 'dashboard.security': '登录与安全', 'dashboard.securityStatus': '安全状态', 'dashboard.pending': '有 {count} 项待处理', 'dashboard.normal': '正常', 'dashboard.emailAndPhone': '邮箱验证；手机号可作为额外安全方式', 'dashboard.sessions': '登录设备', 'dashboard.activeSessions': '当前活跃会话', 'dashboard.authorizations': '应用授权', 'dashboard.revokeAnytime': '可随时撤销', 'dashboard.latestLogin': '最近登录', 'dashboard.loading': '读取中', 'dashboard.noRecords': '暂无记录', 'dashboard.fullHistory': '查看完整登录记录', 'dashboard.securitySection': '账户安全', 'dashboard.securityDescription': '这里只显示需要你处理的事项。', 'dashboard.todos': '还有 {count} 项没有完成', 'dashboard.noTodos': '当前没有需要处理的安全项目', 'dashboard.emailUnverified': '邮箱尚未验证', 'dashboard.sendVerification': '发送验证邮件', 'dashboard.phoneUnbound': '手机号尚未绑定（可选）。', 'dashboard.manageSecurity': '管理安全设置', 'dashboard.recentDevices': '最近设备', 'dashboard.recentDevicesDescription': '近期访问过 MindAuth 用户中心的浏览器与客户端。', 'dashboard.allDevices': '全部设备', 'dashboard.currentDevice': '当前设备', 'dashboard.noDevices': '没有活跃的登录设备。', 'dashboard.appsDescription': '已获准访问账户的应用。', 'dashboard.manageAuthorizations': '管理授权', 'dashboard.noAuthorizations': '没有已授权的应用。', 'dashboard.noScope': '未提供权限说明', 'dashboard.developerApps': '开发者应用', 'dashboard.communityApps': '社区应用', 'dashboard.notifications': '通知', 'dashboard.notificationsDescription': '最近的账户和安全消息。', 'dashboard.notificationCenter': '通知中心', 'dashboard.noNotifications': '暂无需要处理的通知。', 'dashboard.emailSent': '验证邮件已发送。', 'dashboard.emailSendFailed': '发送验证邮件失败。',
  },
  en: {
    'language.label': 'Language', 'language.zh-CN': '简体中文', 'language.en': 'English', 'language.ru': 'Русский', 'language.ja': '日本語',
    'brand.account': 'Account', 'brand.back': 'Back to community', 'brand.powered': 'One account for MDTBBS and its community applications.',
    'brand.tagline': 'Mindustry community', 'brand.description': 'Discover mods, maps, schematics and discussions.', 'brand.visit': 'Visit MDTBBS',
    'auth.continue': 'Sign in to continue to {client}', 'auth.directDescription': 'Use your MindAuth account for community services.', 'auth.login': 'Sign in',
    'auth.register': 'Create account', 'auth.noAccount': 'New here?', 'auth.haveAccount': 'Already have an account?', 'auth.forgot': 'Forgot password', 'auth.usernameOrEmail': 'Username or email',
    'auth.password': 'Password', 'auth.usernamePlaceholder': 'Enter your username or email', 'auth.passwordPlaceholder': 'Enter your password',
    'auth.loginError': 'Sign-in failed', 'auth.connecting': 'Connecting to {client}', 'auth.chooseLogin': 'Choose a sign-in method',
    'auth.passwordTab': 'Password', 'auth.qq': 'QQ', 'auth.qqDescription': 'Sign in with a QQ account linked to MDTBBS.', 'auth.loginWithQQ': 'Continue with QQ',
    'auth.loginSuccess': 'Signed in', 'auth.loginFailed': 'Sign-in failed', 'auth.enterCredentials': 'Enter your username or email and password',
    'oauth.title': 'Review access request', 'oauth.description': 'Check the application and permissions before continuing.',
    'error.emailVerification': 'Verify your email before creating a developer application.', 'error.phoneVerification': 'MDTBBS developer applications require a verified phone number.',
    'nav.dashboard': 'Overview', 'nav.account': 'Account', 'nav.profile': 'Profile', 'nav.security': 'Security', 'nav.sessions': 'Sessions', 'nav.activity': 'Sign-in history', 'nav.apps': 'Applications', 'nav.authorizations': 'Authorized apps', 'nav.messages': 'Messages', 'nav.notifications': 'Notifications', 'nav.developer': 'Developer', 'nav.developerApps': 'My applications',
    'nav.securityGroup': 'Security', 'nav.messagesGroup': 'Messages',
    'legal.terms': 'Terms of Service', 'legal.privacy': 'Privacy Policy', 'legal.about': 'About', 'legal.aria': 'Legal and site information',
    'profile.title': 'Profile', 'profile.description': 'Manage your avatar, banner, username and profile details.', 'profile.avatar': 'Avatar', 'profile.avatarDescription': 'Use a clear image to help identify your account.', 'profile.avatarTitle': 'Account avatar', 'profile.imageTypes': 'JPEG, PNG, GIF or WebP; up to {size} MB.', 'profile.changeAvatar': 'Change avatar', 'profile.remove': 'Remove', 'profile.basic': 'Basic information', 'profile.basicDescription': 'Details used to identify and display your MindAuth account.', 'profile.username': 'Username', 'profile.usernameDescription': 'You can change your username once every 30 days. You will need to sign in again.', 'profile.usernameHint': '2–50 characters. Letters, numbers, underscores, hyphens and Chinese characters are supported.', 'profile.saveUsername': 'Save username', 'profile.email': 'Email', 'profile.emailDescription': 'Your email is used to sign in and recover your account. Change it in Security settings.', 'profile.verified': 'Verified', 'profile.pending': 'Needs verification', 'profile.verifyEmail': 'Verify email', 'profile.createdAt': 'Account created', 'profile.banner': 'Profile banner', 'profile.bannerDescription': 'The banner appears on your profile, not on the account overview.', 'profile.bannerTitle': 'Banner image', 'profile.bannerTypes': 'JPEG, PNG, GIF or WebP; up to 5 MB.', 'profile.bannerPreview': 'Profile banner preview', 'profile.bannerUnset': 'No banner set', 'profile.changeBanner': 'Change banner', 'profile.custom': 'Custom profile fields', 'profile.customDescription': 'Optional fields provided by MindAuth administrators.', 'profile.choose': 'Choose an option', 'profile.required': 'Required', 'profile.optional': 'Optional', 'profile.save': 'Save profile', 'profile.emptyFields': 'There are no custom fields to edit.', 'profile.newUsernameRequired': 'Enter a new username.', 'profile.usernameUpdated': 'Username updated. Sign in again to continue.', 'profile.usernameFailed': 'Could not change username.', 'profile.fieldsSaved': 'Custom profile details saved.', 'profile.fieldsSaveFailed': 'Could not save profile details.', 'profile.imageTooLarge': 'Image must be no larger than {size} MB.', 'profile.avatarUpdated': 'Avatar updated.', 'profile.bannerUpdated': 'Banner updated.', 'profile.uploadFailed': 'Upload failed.', 'profile.avatarDeleted': 'Avatar removed.', 'profile.bannerDeleted': 'Banner removed.', 'profile.deleteFailed': 'Could not remove image.',
    'shared.loading': 'Loading', 'shared.loadFailed': 'Could not load this information. Check your connection and try again.', 'shared.retry': 'Retry',
    'activity.title': 'Sign-in history', 'activity.description': 'Review recent sign-in activity recorded by MindAuth.', 'activity.recent': 'Recent sign-ins', 'activity.details': 'This record includes time, client, IP address and sign-in method. Location and failed attempts are not available.', 'activity.time': 'Time', 'activity.client': 'Client', 'activity.ip': 'IP address', 'activity.method': 'Method', 'activity.notProvided': 'Not provided', 'activity.empty': 'No sign-in history yet.', 'activity.web': 'Web sign-in', 'activity.oauth': 'OAuth sign-in', 'activity.native': 'Native app sign-in', 'activity.social': 'Linked account sign-in', 'activity.generic': 'Sign-in',
    'authorization.title': 'Authorized apps', 'authorization.description': 'Review apps connected to your MindAuth account and the access they have.', 'authorization.current': 'Current authorizations', 'authorization.currentDescription': 'Revoking access also invalidates the app’s related tokens.', 'authorization.public': 'Public client', 'authorization.confidential': 'Confidential client', 'authorization.thirdParty': 'Third-party app', 'authorization.firstParty': 'First-party app', 'authorization.revoke': 'Revoke access', 'authorization.created': 'Authorized on', 'authorization.lastUsed': 'Last used', 'authorization.noRecentUse': 'No recent use', 'authorization.scope': 'Permissions', 'authorization.noScope': 'No permissions provided', 'authorization.empty': 'No apps are authorized.', 'authorization.revokeTitle': 'Revoke app access', 'authorization.cancel': 'Cancel', 'authorization.confirm': 'Confirm revocation', 'authorization.revokeBody': 'After access for {client} is revoked, this app can no longer access your account and its related tokens will stop working.', 'authorization.revoked': 'Access for {client} was revoked.', 'authorization.failed': 'Could not revoke app access.',
    'notification.title': 'Notifications', 'notification.description': 'Account, security and service messages from MindAuth.', 'notification.center': 'Notification center', 'notification.count': '{count} notifications', 'notification.latest': 'Recent account messages appear here.', 'notification.markAll': 'Mark all as read', 'notification.unread': 'Unread', 'notification.markRead': 'Mark as read', 'notification.delete': 'Delete', 'notification.empty': 'No notifications to show.', 'notification.pageLabel': 'Notification pages', 'notification.previous': 'Previous', 'notification.next': 'Next', 'notification.page': 'Page {page} of {total}', 'notification.readAllSuccess': 'All notifications marked as read.', 'notification.readAllFailed': 'Could not mark notifications as read.', 'notification.deleteFailed': 'Could not delete notification.',
    'session.title': 'Sessions', 'session.description': 'Review browsers and apps that have used your account, and end sessions you no longer need.', 'session.current': 'Current device', 'session.currentDescription': 'The current session remains active unless you choose to end it.', 'session.others': 'Other devices', 'session.othersDescription': 'End sessions on devices you do not recognize or no longer use.', 'session.revokeAll': 'Sign out other devices', 'session.noCurrent': 'No active session was found for this browser.', 'session.noOthers': 'No other signed-in devices.', 'session.confirmAll': 'Sign out other devices?', 'session.confirmDevice': 'Sign out this device?', 'session.cancel': 'Cancel', 'session.confirm': 'Sign out', 'session.bodyAll': 'This will sign out {count} other devices. Your current device stays signed in.', 'session.bodyCurrent': 'This ends your current MindAuth session.', 'session.bodyOther': 'This device will need to sign in again to use MindAuth.', 'session.currentLabel': 'Current device', 'session.native': 'Native app', 'session.browser': 'Web browser', 'session.ipMissing': 'IP address not provided', 'session.recentActivity': 'Last active', 'session.loginTime': 'Signed in', 'session.signOutCurrent': 'Sign out this device', 'session.signOut': 'Sign out device', 'session.signedOut': 'Device signed out.', 'session.currentSignedOut': 'Current device signed out.', 'session.otherSignedOut': 'All other devices signed out.', 'session.partialFailure': 'Signed out {success} devices; {failed} could not be signed out.', 'session.revokeFailed': 'Could not sign out device.',
    'dashboard.title': 'Account', 'dashboard.description': 'Review account status, security settings, sessions and app access.', 'dashboard.identity': 'Account identity', 'dashboard.status': 'Account status', 'dashboard.emailVerified': 'Email verified', 'dashboard.emailPending': 'Email needs verification', 'dashboard.phoneBound': 'Phone number added', 'dashboard.phoneOptional': 'Phone number (optional)', 'dashboard.profile': 'Profile', 'dashboard.security': 'Sign-in and security', 'dashboard.securityStatus': 'Security status', 'dashboard.pending': '{count} items need attention', 'dashboard.normal': 'Good', 'dashboard.emailAndPhone': 'Email verification; a phone number is optional security', 'dashboard.sessions': 'Sessions', 'dashboard.activeSessions': 'Active sessions', 'dashboard.authorizations': 'App access', 'dashboard.revokeAnytime': 'Can be revoked anytime', 'dashboard.latestLogin': 'Recent sign-in', 'dashboard.loading': 'Loading', 'dashboard.noRecords': 'No records', 'dashboard.fullHistory': 'View sign-in history', 'dashboard.securitySection': 'Account security', 'dashboard.securityDescription': 'Only items that need your attention appear here.', 'dashboard.todos': '{count} items still need attention', 'dashboard.noTodos': 'No security items need your attention.', 'dashboard.emailUnverified': 'Email is not verified', 'dashboard.sendVerification': 'Send verification email', 'dashboard.phoneUnbound': 'A phone number is not added (optional).', 'dashboard.manageSecurity': 'Manage security settings', 'dashboard.recentDevices': 'Recent devices', 'dashboard.recentDevicesDescription': 'Browsers and apps that recently accessed your MindAuth account.', 'dashboard.allDevices': 'All devices', 'dashboard.currentDevice': 'Current device', 'dashboard.noDevices': 'No active sessions.', 'dashboard.appsDescription': 'Apps authorized to access your account.', 'dashboard.manageAuthorizations': 'Manage access', 'dashboard.noAuthorizations': 'No apps are authorized.', 'dashboard.noScope': 'No permission details', 'dashboard.developerApps': 'Developer apps', 'dashboard.communityApps': 'Community apps', 'dashboard.notifications': 'Notifications', 'dashboard.notificationsDescription': 'Recent account and security messages.', 'dashboard.notificationCenter': 'Notification center', 'dashboard.noNotifications': 'No notifications to show.', 'dashboard.emailSent': 'Verification email sent.', 'dashboard.emailSendFailed': 'Could not send the verification email.',
  },
  ru: {
    'language.label': 'Язык', 'language.zh-CN': '简体中文', 'language.en': 'English', 'language.ru': 'Русский', 'language.ja': '日本語',
    'brand.account': 'Аккаунт', 'brand.back': 'К сообществу', 'brand.powered': 'Единый аккаунт для MDTBBS и связанных приложений сообщества.',
    'brand.tagline': 'Сообщество Mindustry', 'brand.description': 'Моды, карты, схемы и обсуждения.', 'brand.visit': 'Открыть MDTBBS',
    'auth.continue': 'Войдите, чтобы продолжить в {client}', 'auth.directDescription': 'Используйте аккаунт MindAuth для сервисов сообщества.', 'auth.login': 'Войти',
    'auth.register': 'Создать аккаунт', 'auth.noAccount': 'Впервые здесь?', 'auth.haveAccount': 'Уже есть аккаунт?', 'auth.forgot': 'Забыли пароль?', 'auth.usernameOrEmail': 'Имя пользователя или почта',
    'auth.password': 'Пароль', 'auth.usernamePlaceholder': 'Введите имя пользователя или почту', 'auth.passwordPlaceholder': 'Введите пароль',
    'auth.loginError': 'Не удалось войти', 'auth.connecting': 'Подключение к приложению: {client}', 'auth.chooseLogin': 'Выберите способ входа',
    'auth.passwordTab': 'Пароль', 'auth.qq': 'QQ', 'auth.qqDescription': 'Войдите через QQ, связанный с MDTBBS.', 'auth.loginWithQQ': 'Войти через QQ',
    'auth.loginSuccess': 'Вы вошли', 'auth.loginFailed': 'Не удалось войти', 'auth.enterCredentials': 'Введите имя пользователя или почту и пароль',
    'oauth.title': 'Проверка доступа приложения', 'oauth.description': 'Проверьте приложение и запрашиваемые разрешения.',
    'error.emailVerification': 'Подтвердите почту, чтобы создать приложение разработчика.', 'error.phoneVerification': 'Для приложений экосистемы MDTBBS нужен подтверждённый номер телефона.',
    'nav.dashboard': 'Обзор', 'nav.account': 'Аккаунт', 'nav.profile': 'Профиль', 'nav.security': 'Безопасность', 'nav.sessions': 'Сеансы', 'nav.activity': 'История входов', 'nav.apps': 'Приложения', 'nav.authorizations': 'Разрешённые приложения', 'nav.messages': 'Сообщения', 'nav.notifications': 'Уведомления', 'nav.developer': 'Разработка', 'nav.developerApps': 'Мои приложения',
    'nav.securityGroup': 'Безопасность', 'nav.messagesGroup': 'Сообщения',
    'legal.terms': 'Условия использования', 'legal.privacy': 'Политика конфиденциальности', 'legal.about': 'О проекте', 'legal.aria': 'Правовая информация',
    'profile.title': 'Профиль', 'profile.description': 'Управляйте аватаром, обложкой, именем и данными профиля.', 'profile.avatar': 'Аватар', 'profile.avatarDescription': 'Добавьте чёткое изображение, чтобы вас было легче узнать.', 'profile.avatarTitle': 'Аватар аккаунта', 'profile.imageTypes': 'JPEG, PNG, GIF или WebP; до {size} МБ.', 'profile.changeAvatar': 'Сменить аватар', 'profile.remove': 'Удалить', 'profile.basic': 'Основные данные', 'profile.basicDescription': 'Информация для отображения и идентификации аккаунта MindAuth.', 'profile.username': 'Имя пользователя', 'profile.usernameDescription': 'Имя можно менять раз в 30 дней. После изменения потребуется войти снова.', 'profile.usernameHint': '2–50 символов: латинские буквы, цифры, подчёркивание, дефис и китайские иероглифы.', 'profile.saveUsername': 'Сохранить имя', 'profile.email': 'Почта', 'profile.emailDescription': 'Почта используется для входа и восстановления аккаунта. Изменить её можно в настройках безопасности.', 'profile.verified': 'Подтверждена', 'profile.pending': 'Не подтверждена', 'profile.verifyEmail': 'Подтвердить почту', 'profile.createdAt': 'Аккаунт создан', 'profile.banner': 'Обложка профиля', 'profile.bannerDescription': 'Обложка видна в профиле, но не в сводке аккаунта.', 'profile.bannerTitle': 'Изображение обложки', 'profile.bannerTypes': 'JPEG, PNG, GIF или WebP; до 5 МБ.', 'profile.bannerPreview': 'Предпросмотр обложки', 'profile.bannerUnset': 'Обложка не задана', 'profile.changeBanner': 'Сменить обложку', 'profile.custom': 'Дополнительные поля', 'profile.customDescription': 'Необязательные поля, заданные администраторами MindAuth.', 'profile.choose': 'Выберите вариант', 'profile.required': 'Обязательно', 'profile.optional': 'Необязательно', 'profile.save': 'Сохранить профиль', 'profile.emptyFields': 'Нет дополнительных полей для редактирования.', 'profile.newUsernameRequired': 'Введите новое имя пользователя.', 'profile.usernameUpdated': 'Имя изменено. Войдите снова.', 'profile.usernameFailed': 'Не удалось изменить имя.', 'profile.fieldsSaved': 'Данные профиля сохранены.', 'profile.fieldsSaveFailed': 'Не удалось сохранить данные профиля.', 'profile.imageTooLarge': 'Размер изображения не должен превышать {size} МБ.', 'profile.avatarUpdated': 'Аватар обновлён.', 'profile.bannerUpdated': 'Обложка обновлена.', 'profile.uploadFailed': 'Не удалось загрузить изображение.', 'profile.avatarDeleted': 'Аватар удалён.', 'profile.bannerDeleted': 'Обложка удалена.', 'profile.deleteFailed': 'Не удалось удалить изображение.',
    'shared.loading': 'Загрузка', 'shared.loadFailed': 'Не удалось загрузить данные. Проверьте соединение и повторите попытку.', 'shared.retry': 'Повторить',
    'activity.title': 'История входов', 'activity.description': 'Недавние входы, сохранённые MindAuth.', 'activity.recent': 'Недавние входы', 'activity.details': 'В записи доступны время, приложение, IP-адрес и способ входа. Данные о местоположении и неудачных попытках не собираются.', 'activity.time': 'Время', 'activity.client': 'Приложение', 'activity.ip': 'IP-адрес', 'activity.method': 'Способ входа', 'activity.notProvided': 'Не указано', 'activity.empty': 'Истории входов пока нет.', 'activity.web': 'Вход через веб-сайт', 'activity.oauth': 'Вход через OAuth', 'activity.native': 'Вход из приложения', 'activity.social': 'Вход через связанный аккаунт', 'activity.generic': 'Вход',
    'authorization.title': 'Разрешённые приложения', 'authorization.description': 'Приложения, подключённые к MindAuth, и предоставленный им доступ.', 'authorization.current': 'Текущие разрешения', 'authorization.currentDescription': 'Отзыв доступа также отключает связанные токены приложения.', 'authorization.public': 'Публичный клиент', 'authorization.confidential': 'Конфиденциальный клиент', 'authorization.thirdParty': 'Стороннее приложение', 'authorization.firstParty': 'Официальное приложение', 'authorization.revoke': 'Отозвать доступ', 'authorization.created': 'Разрешено', 'authorization.lastUsed': 'Последнее использование', 'authorization.noRecentUse': 'Нет данных', 'authorization.scope': 'Права доступа', 'authorization.noScope': 'Права не указаны', 'authorization.empty': 'Нет разрешённых приложений.', 'authorization.revokeTitle': 'Отозвать доступ приложения', 'authorization.cancel': 'Отмена', 'authorization.confirm': 'Отозвать', 'authorization.revokeBody': 'После отзыва доступа для {client} приложение больше не сможет обращаться к аккаунту, а его токены перестанут работать.', 'authorization.revoked': 'Доступ для {client} отозван.', 'authorization.failed': 'Не удалось отозвать доступ.',
    'notification.title': 'Уведомления', 'notification.description': 'Сообщения MindAuth об аккаунте, безопасности и сервисе.', 'notification.center': 'Центр уведомлений', 'notification.count': 'Уведомлений: {count}', 'notification.latest': 'Здесь появятся последние сообщения аккаунта.', 'notification.markAll': 'Отметить все как прочитанные', 'notification.unread': 'Не прочитано', 'notification.markRead': 'Отметить прочитанным', 'notification.delete': 'Удалить', 'notification.empty': 'Нет уведомлений.', 'notification.pageLabel': 'Страницы уведомлений', 'notification.previous': 'Назад', 'notification.next': 'Далее', 'notification.page': 'Страница {page} из {total}', 'notification.readAllSuccess': 'Все уведомления отмечены прочитанными.', 'notification.readAllFailed': 'Не удалось отметить уведомления.', 'notification.deleteFailed': 'Не удалось удалить уведомление.',
    'session.title': 'Сеансы', 'session.description': 'Просматривайте браузеры и приложения, использовавшие аккаунт, и завершайте ненужные сеансы.', 'session.current': 'Это устройство', 'session.currentDescription': 'Текущий сеанс завершится только по вашему запросу.', 'session.others': 'Другие устройства', 'session.othersDescription': 'Завершите сеансы на незнакомых или неиспользуемых устройствах.', 'session.revokeAll': 'Выйти на других устройствах', 'session.noCurrent': 'Активный сеанс этого браузера не найден.', 'session.noOthers': 'Других активных устройств нет.', 'session.confirmAll': 'Выйти на других устройствах?', 'session.confirmDevice': 'Выйти на этом устройстве?', 'session.cancel': 'Отмена', 'session.confirm': 'Выйти', 'session.bodyAll': 'Вы выйдете на других устройствах: {count}. На текущем устройстве вход останется активным.', 'session.bodyCurrent': 'Это завершит текущий сеанс MindAuth.', 'session.bodyOther': 'Чтобы пользоваться MindAuth на этом устройстве, потребуется войти снова.', 'session.currentLabel': 'Текущее устройство', 'session.native': 'Приложение', 'session.browser': 'Веб-браузер', 'session.ipMissing': 'IP-адрес не указан', 'session.recentActivity': 'Активность', 'session.loginTime': 'Вход', 'session.signOutCurrent': 'Выйти на этом устройстве', 'session.signOut': 'Завершить сеанс', 'session.signedOut': 'Сеанс завершён.', 'session.currentSignedOut': 'Текущий сеанс завершён.', 'session.otherSignedOut': 'На остальных устройствах выполнен выход.', 'session.partialFailure': 'Выход выполнен на устройствах: {success}; не удалось: {failed}.', 'session.revokeFailed': 'Не удалось завершить сеанс.',
    'dashboard.title': 'Аккаунт', 'dashboard.description': 'Состояние аккаунта, безопасность, сеансы и доступ приложений.', 'dashboard.identity': 'Данные аккаунта', 'dashboard.status': 'Состояние аккаунта', 'dashboard.emailVerified': 'Почта подтверждена', 'dashboard.emailPending': 'Почту нужно подтвердить', 'dashboard.phoneBound': 'Телефон добавлен', 'dashboard.phoneOptional': 'Телефон (необязательно)', 'dashboard.profile': 'Профиль', 'dashboard.security': 'Вход и безопасность', 'dashboard.securityStatus': 'Безопасность', 'dashboard.pending': 'Требуют внимания: {count}', 'dashboard.normal': 'В порядке', 'dashboard.emailAndPhone': 'Подтверждение почты; телефон можно добавить для защиты', 'dashboard.sessions': 'Сеансы', 'dashboard.activeSessions': 'Активные сеансы', 'dashboard.authorizations': 'Доступ приложений', 'dashboard.revokeAnytime': 'Можно отозвать в любое время', 'dashboard.latestLogin': 'Последний вход', 'dashboard.loading': 'Загрузка', 'dashboard.noRecords': 'Нет данных', 'dashboard.fullHistory': 'История входов', 'dashboard.securitySection': 'Безопасность аккаунта', 'dashboard.securityDescription': 'Здесь показаны только пункты, требующие внимания.', 'dashboard.todos': 'Требуют внимания: {count}', 'dashboard.noTodos': 'Нет нерешённых вопросов безопасности.', 'dashboard.emailUnverified': 'Почта не подтверждена', 'dashboard.sendVerification': 'Отправить письмо для подтверждения', 'dashboard.phoneUnbound': 'Телефон не добавлен (необязательно).', 'dashboard.manageSecurity': 'Настройки безопасности', 'dashboard.recentDevices': 'Недавние устройства', 'dashboard.recentDevicesDescription': 'Браузеры и приложения, недавно использовавшие аккаунт MindAuth.', 'dashboard.allDevices': 'Все устройства', 'dashboard.currentDevice': 'Это устройство', 'dashboard.noDevices': 'Активных сеансов нет.', 'dashboard.appsDescription': 'Приложения, которым разрешён доступ к аккаунту.', 'dashboard.manageAuthorizations': 'Управление доступом', 'dashboard.noAuthorizations': 'Разрешённых приложений нет.', 'dashboard.noScope': 'Описание прав не указано', 'dashboard.developerApps': 'Приложения разработчика', 'dashboard.communityApps': 'Приложения сообщества', 'dashboard.notifications': 'Уведомления', 'dashboard.notificationsDescription': 'Недавние сообщения об аккаунте и безопасности.', 'dashboard.notificationCenter': 'Центр уведомлений', 'dashboard.noNotifications': 'Уведомлений нет.', 'dashboard.emailSent': 'Письмо для подтверждения отправлено.', 'dashboard.emailSendFailed': 'Не удалось отправить письмо для подтверждения.',
  },
  ja: {
    'language.label': '言語', 'language.zh-CN': '简体中文', 'language.en': 'English', 'language.ru': 'Русский', 'language.ja': '日本語',
    'brand.account': 'アカウント', 'brand.back': 'コミュニティに戻る', 'brand.powered': 'MDTBBS と関連コミュニティアプリの共通アカウントです。',
    'brand.tagline': 'Mindustry コミュニティ', 'brand.description': 'Mod、マップ、設計図、ディスカッション。', 'brand.visit': 'MDTBBS を見る',
    'auth.continue': '{client} を続けるにはログインしてください', 'auth.directDescription': 'MindAuth アカウントでコミュニティサービスを利用できます。', 'auth.login': 'ログイン',
    'auth.register': 'アカウントを作成', 'auth.noAccount': '初めてですか？', 'auth.haveAccount': 'すでにアカウントをお持ちですか？', 'auth.forgot': 'パスワードをお忘れですか', 'auth.usernameOrEmail': 'ユーザー名またはメールアドレス',
    'auth.password': 'パスワード', 'auth.usernamePlaceholder': 'ユーザー名またはメールアドレスを入力', 'auth.passwordPlaceholder': 'パスワードを入力',
    'auth.loginError': 'ログインできませんでした', 'auth.connecting': 'アプリに接続中: {client}', 'auth.chooseLogin': 'ログイン方法を選択',
    'auth.passwordTab': 'パスワード', 'auth.qq': 'QQ', 'auth.qqDescription': 'MDTBBS に連携した QQ アカウントでログインします。', 'auth.loginWithQQ': 'QQ で続ける',
    'auth.loginSuccess': 'ログインしました', 'auth.loginFailed': 'ログインできませんでした', 'auth.enterCredentials': 'ユーザー名またはメールアドレスとパスワードを入力してください',
    'oauth.title': 'アプリのアクセスを確認', 'oauth.description': 'アプリ名と要求されている権限を確認してください。',
    'error.emailVerification': '開発者アプリを作成する前にメールアドレスを確認してください。', 'error.phoneVerification': 'MDTBBS の開発者アプリには電話番号の確認が必要です。',
    'nav.dashboard': '概要', 'nav.account': 'アカウント', 'nav.profile': 'プロフィール', 'nav.security': 'セキュリティ', 'nav.sessions': 'セッション', 'nav.activity': 'ログイン履歴', 'nav.apps': 'アプリ', 'nav.authorizations': '許可したアプリ', 'nav.messages': 'メッセージ', 'nav.notifications': '通知', 'nav.developer': '開発者', 'nav.developerApps': 'アプリ管理',
    'nav.securityGroup': 'セキュリティ', 'nav.messagesGroup': 'メッセージ',
    'legal.terms': '利用規約', 'legal.privacy': 'プライバシーポリシー', 'legal.about': 'このサイトについて', 'legal.aria': '法的情報とサイト情報',
    'profile.title': 'プロフィール', 'profile.description': 'アバター、バナー、ユーザー名、プロフィール情報を管理します。', 'profile.avatar': 'アバター', 'profile.avatarDescription': 'アカウントを識別しやすい画像を設定できます。', 'profile.avatarTitle': 'アカウントのアバター', 'profile.imageTypes': 'JPEG、PNG、GIF、WebP に対応。最大 {size} MB。', 'profile.changeAvatar': 'アバターを変更', 'profile.remove': '削除', 'profile.basic': '基本情報', 'profile.basicDescription': 'MindAuth アカウントの表示と識別に使う情報です。', 'profile.username': 'ユーザー名', 'profile.usernameDescription': '変更は 30 日に 1 回までです。変更後は再ログインが必要です。', 'profile.usernameHint': '2～50 文字。英字、数字、アンダースコア、ハイフン、中国語に対応しています。', 'profile.saveUsername': 'ユーザー名を保存', 'profile.email': 'メールアドレス', 'profile.emailDescription': 'ログインとアカウント復旧に使用します。変更はセキュリティ設定から行えます。', 'profile.verified': '確認済み', 'profile.pending': '未確認', 'profile.verifyEmail': 'メールを確認', 'profile.createdAt': 'アカウント作成日', 'profile.banner': 'プロフィールバナー', 'profile.bannerDescription': 'バナーはプロフィールに表示され、アカウント概要には表示されません。', 'profile.bannerTitle': 'バナー画像', 'profile.bannerTypes': 'JPEG、PNG、GIF、WebP に対応。最大 5 MB。', 'profile.bannerPreview': 'プロフィールバナーのプレビュー', 'profile.bannerUnset': 'バナーは未設定です', 'profile.changeBanner': 'バナーを変更', 'profile.custom': 'カスタムプロフィール項目', 'profile.customDescription': 'MindAuth 管理者が提供する任意の項目です。', 'profile.choose': '選択してください', 'profile.required': '必須', 'profile.optional': '任意', 'profile.save': 'プロフィールを保存', 'profile.emptyFields': '編集できるカスタム項目はありません。', 'profile.newUsernameRequired': '新しいユーザー名を入力してください。', 'profile.usernameUpdated': 'ユーザー名を変更しました。再ログインしてください。', 'profile.usernameFailed': 'ユーザー名を変更できませんでした。', 'profile.fieldsSaved': 'プロフィール情報を保存しました。', 'profile.fieldsSaveFailed': 'プロフィール情報を保存できませんでした。', 'profile.imageTooLarge': '画像は {size} MB 以下にしてください。', 'profile.avatarUpdated': 'アバターを更新しました。', 'profile.bannerUpdated': 'バナーを更新しました。', 'profile.uploadFailed': '画像をアップロードできませんでした。', 'profile.avatarDeleted': 'アバターを削除しました。', 'profile.bannerDeleted': 'バナーを削除しました。', 'profile.deleteFailed': '画像を削除できませんでした。',
    'shared.loading': '読み込み中', 'shared.loadFailed': '情報を読み込めませんでした。接続を確認して再試行してください。', 'shared.retry': '再試行',
    'activity.title': 'ログイン履歴', 'activity.description': 'MindAuth に記録された最近のログインを確認できます。', 'activity.recent': '最近のログイン', 'activity.details': '記録には時刻、アプリ、IP アドレス、ログイン方法が含まれます。場所や失敗したログインは記録されません。', 'activity.time': '日時', 'activity.client': 'アプリ', 'activity.ip': 'IP アドレス', 'activity.method': '方法', 'activity.notProvided': '未提供', 'activity.empty': 'ログイン履歴はありません。', 'activity.web': 'Web ログイン', 'activity.oauth': 'OAuth ログイン', 'activity.native': 'アプリからログイン', 'activity.social': '連携アカウントでログイン', 'activity.generic': 'ログイン',
    'authorization.title': '許可したアプリ', 'authorization.description': 'MindAuth アカウントに接続したアプリと、そのアクセス権を確認できます。', 'authorization.current': '現在の許可', 'authorization.currentDescription': 'アクセスを取り消すと、関連するトークンも無効になります。', 'authorization.public': 'パブリッククライアント', 'authorization.confidential': '機密クライアント', 'authorization.thirdParty': 'サードパーティアプリ', 'authorization.firstParty': '公式アプリ', 'authorization.revoke': 'アクセスを取り消す', 'authorization.created': '許可日時', 'authorization.lastUsed': '最終使用', 'authorization.noRecentUse': '記録なし', 'authorization.scope': '権限', 'authorization.noScope': '権限情報なし', 'authorization.empty': '許可したアプリはありません。', 'authorization.revokeTitle': 'アプリのアクセスを取り消す', 'authorization.cancel': 'キャンセル', 'authorization.confirm': '取り消す', 'authorization.revokeBody': '{client} のアクセスを取り消すと、このアプリはアカウントにアクセスできなくなり、関連トークンも無効になります。', 'authorization.revoked': '{client} のアクセスを取り消しました。', 'authorization.failed': 'アクセスを取り消せませんでした。',
    'notification.title': '通知', 'notification.description': 'MindAuth からのアカウント・セキュリティ・サービス通知です。', 'notification.center': '通知センター', 'notification.count': '通知 {count} 件', 'notification.latest': '最近のアカウント通知がここに表示されます。', 'notification.markAll': 'すべて既読にする', 'notification.unread': '未読', 'notification.markRead': '既読にする', 'notification.delete': '削除', 'notification.empty': '通知はありません。', 'notification.pageLabel': '通知ページ', 'notification.previous': '前へ', 'notification.next': '次へ', 'notification.page': '{total} ページ中 {page} ページ', 'notification.readAllSuccess': 'すべての通知を既読にしました。', 'notification.readAllFailed': '通知を既読にできませんでした。', 'notification.deleteFailed': '通知を削除できませんでした。',
    'session.title': 'セッション', 'session.description': 'アカウントを使用したブラウザーやアプリを確認し、不要なセッションを終了できます。', 'session.current': '現在の端末', 'session.currentDescription': '現在のセッションは、明示的に終了するまで維持されます。', 'session.others': 'その他の端末', 'session.othersDescription': '見覚えのない端末や使っていない端末のセッションを終了してください。', 'session.revokeAll': '他の端末からログアウト', 'session.noCurrent': 'このブラウザーの有効なセッションが見つかりません。', 'session.noOthers': '他にログイン中の端末はありません。', 'session.confirmAll': '他の端末からログアウトしますか？', 'session.confirmDevice': 'この端末からログアウトしますか？', 'session.cancel': 'キャンセル', 'session.confirm': 'ログアウト', 'session.bodyAll': '他の端末 {count} 台からログアウトします。現在の端末には引き続きログインできます。', 'session.bodyCurrent': '現在の MindAuth セッションを終了します。', 'session.bodyOther': 'この端末で MindAuth を使うには、再度ログインが必要です。', 'session.currentLabel': '現在の端末', 'session.native': 'アプリ', 'session.browser': 'Web ブラウザー', 'session.ipMissing': 'IP アドレスなし', 'session.recentActivity': '最終利用', 'session.loginTime': 'ログイン日時', 'session.signOutCurrent': 'この端末からログアウト', 'session.signOut': '端末をログアウト', 'session.signedOut': '端末からログアウトしました。', 'session.currentSignedOut': '現在の端末からログアウトしました。', 'session.otherSignedOut': '他のすべての端末からログアウトしました。', 'session.partialFailure': '{success} 台からログアウトしました。{failed} 台は失敗しました。', 'session.revokeFailed': '端末からログアウトできませんでした。',
    'dashboard.title': 'アカウント', 'dashboard.description': 'アカウントの状態、セキュリティ、セッション、アプリのアクセスを確認します。', 'dashboard.identity': 'アカウント情報', 'dashboard.status': 'アカウントの状態', 'dashboard.emailVerified': 'メール確認済み', 'dashboard.emailPending': 'メール未確認', 'dashboard.phoneBound': '電話番号登録済み', 'dashboard.phoneOptional': '電話番号（任意）', 'dashboard.profile': 'プロフィール', 'dashboard.security': 'ログインとセキュリティ', 'dashboard.securityStatus': 'セキュリティ状態', 'dashboard.pending': '要対応：{count} 件', 'dashboard.normal': '問題ありません', 'dashboard.emailAndPhone': 'メール確認済みかどうか。電話番号は任意の追加保護です', 'dashboard.sessions': 'セッション', 'dashboard.activeSessions': '有効なセッション', 'dashboard.authorizations': 'アプリのアクセス', 'dashboard.revokeAnytime': 'いつでも取り消せます', 'dashboard.latestLogin': '最近のログイン', 'dashboard.loading': '読み込み中', 'dashboard.noRecords': '記録なし', 'dashboard.fullHistory': 'ログイン履歴を見る', 'dashboard.securitySection': 'アカウントの安全', 'dashboard.securityDescription': '対応が必要な項目だけを表示します。', 'dashboard.todos': '未完了：{count} 件', 'dashboard.noTodos': '対応が必要なセキュリティ項目はありません。', 'dashboard.emailUnverified': 'メールアドレスが未確認です', 'dashboard.sendVerification': '確認メールを送信', 'dashboard.phoneUnbound': '電話番号は未登録です（任意）。', 'dashboard.manageSecurity': 'セキュリティ設定', 'dashboard.recentDevices': '最近の端末', 'dashboard.recentDevicesDescription': 'MindAuth アカウントに最近アクセスしたブラウザーやアプリです。', 'dashboard.allDevices': 'すべての端末', 'dashboard.currentDevice': '現在の端末', 'dashboard.noDevices': '有効なセッションはありません。', 'dashboard.appsDescription': 'アカウントへのアクセスを許可したアプリです。', 'dashboard.manageAuthorizations': 'アクセスを管理', 'dashboard.noAuthorizations': '許可したアプリはありません。', 'dashboard.noScope': '権限の説明なし', 'dashboard.developerApps': '開発者アプリ', 'dashboard.communityApps': 'コミュニティアプリ', 'dashboard.notifications': '通知', 'dashboard.notificationsDescription': '最近のアカウントとセキュリティに関する通知です。', 'dashboard.notificationCenter': '通知センター', 'dashboard.noNotifications': '通知はありません。', 'dashboard.emailSent': '確認メールを送信しました。', 'dashboard.emailSendFailed': '確認メールを送信できませんでした。',
  },
};

export function normalizeLocale(value: string | null | undefined): Locale | null {
  const normalized = String(value || '').trim().toLowerCase();
  if (normalized === 'zh' || normalized.startsWith('zh-cn')) return 'zh-CN';
  if (normalized === 'en' || normalized.startsWith('en-')) return 'en';
  if (normalized === 'ru' || normalized.startsWith('ru-')) return 'ru';
  if (normalized === 'ja' || normalized.startsWith('ja-')) return 'ja';
  return null;
}

export function translate(locale: Locale, key: string, values: Record<string, string | number> = {}) {
  const template = messages[locale][key] || messages.en[key] || key;
  return template.replace(/\{(\w+)\}/g, (_, name: string) => String(values[name] ?? ''));
}
