export const oauthMessages = {
  'zh-CN': {
    'oauth.invalidConfiguration': '此应用的登录配置有误，请联系开发者。', 'oauth.unavailable': '暂时无法验证此授权请求，请稍后重试。', 'oauth.submitFailed': '无法提交授权决定，请稍后重试。', 'oauth.verifying': '正在验证授权请求…', 'oauth.official': '官方应用', 'oauth.thirdParty': '第三方应用', 'oauth.developerBy': '由 {name} 开发', 'oauth.officialProvider': '由 MindAuth 社区团队提供', 'oauth.missingDescription': '此应用将使用 MindAuth 账户安全登录，并访问其申请的社区权限。', 'oauth.newScopes': '此应用新增申请以下权限', 'oauth.requestedScopes': '此应用申请以下权限', 'oauth.sensitive': '敏感权限', 'oauth.previousConsent': '你之前已允许部分权限；确认后会把本次申请的权限加入此应用授权。', 'oauth.details': '应用详情', 'oauth.clientId': 'Client ID', 'oauth.redirectHost': '回调主机', 'oauth.website': '应用主页', 'oauth.developer': '开发者', 'oauth.revokeNotice': '你可以随时在 MindAuth 账户中心撤销应用访问。MDTBBS 社区的账号状态和站点规则仍然适用。', 'oauth.cancel': '取消', 'oauth.approve': '允许', 'oauth.submitting': '提交中…', 'oauth.registeredCallback': '已登记的回调地址',
    'oauth.scope.openid': '账户标识', 'oauth.scope.profile': '基本资料', 'oauth.scope.email': '邮箱地址', 'oauth.scope.forum.read': '浏览社区内容', 'oauth.scope.forum.write': '发布社区内容', 'oauth.scope.resource.read': '浏览资源', 'oauth.scope.resource.download': '下载资源', 'oauth.scope.resource.upload': '上传资源', 'oauth.scope.notification.read': '读取通知', 'oauth.scope.message.read': '读取私信', 'oauth.scope.message.write': '发送私信',
    'oauth.scopeDesc.openid': '读取用于识别账户的稳定标识。', 'oauth.scopeDesc.profile': '读取用户名、头像等基本资料。', 'oauth.scopeDesc.email': '读取邮箱地址和验证状态。', 'oauth.scopeDesc.forum.read': '读取你有权限查看的帖子和回复。', 'oauth.scopeDesc.forum.write': '以你的身份发布帖子、回复或进行相关操作。', 'oauth.scopeDesc.resource.read': '读取地图、蓝图、Mod 等资源信息。', 'oauth.scopeDesc.resource.download': '使用你的账户下载公开资源。', 'oauth.scopeDesc.resource.upload': '以你的身份提交地图、蓝图、Mod 等资源。', 'oauth.scopeDesc.notification.read': '读取账户收到的通知。', 'oauth.scopeDesc.message.read': '读取你的私信和会话内容。', 'oauth.scopeDesc.message.write': '以你的身份向其他用户发送私信。',
  },
  en: {
    'oauth.invalidConfiguration': 'This application has an invalid sign-in configuration. Contact its developer.', 'oauth.unavailable': 'We could not verify this access request. Try again later.', 'oauth.submitFailed': 'We could not submit your choice. Try again later.', 'oauth.verifying': 'Verifying access request…', 'oauth.official': 'Official application', 'oauth.thirdParty': 'Third-party application', 'oauth.developerBy': 'Developed by {name}', 'oauth.officialProvider': 'Provided by the MindAuth community team', 'oauth.missingDescription': 'This application will use your MindAuth account to sign in securely and access the community permissions it requests.', 'oauth.newScopes': 'This application is requesting additional permissions', 'oauth.requestedScopes': 'This application is requesting these permissions', 'oauth.sensitive': 'Sensitive permission', 'oauth.previousConsent': 'You have already granted some permissions. Continuing will add these requested permissions to the application’s access.', 'oauth.details': 'Application details', 'oauth.clientId': 'Client ID', 'oauth.redirectHost': 'Redirect host', 'oauth.website': 'Application website', 'oauth.developer': 'Developer', 'oauth.revokeNotice': 'You can revoke this application’s access at any time from your MindAuth account. Community account status and site rules still apply.', 'oauth.cancel': 'Cancel', 'oauth.approve': 'Allow', 'oauth.submitting': 'Submitting…', 'oauth.registeredCallback': 'Registered redirect URI',
    'oauth.scope.openid': 'Account identifier', 'oauth.scope.profile': 'Basic profile', 'oauth.scope.email': 'Email address', 'oauth.scope.forum.read': 'Browse community content', 'oauth.scope.forum.write': 'Publish community content', 'oauth.scope.resource.read': 'Browse resources', 'oauth.scope.resource.download': 'Download resources', 'oauth.scope.resource.upload': 'Upload resources', 'oauth.scope.notification.read': 'Read notifications', 'oauth.scope.message.read': 'Read private messages', 'oauth.scope.message.write': 'Send private messages',
    'oauth.scopeDesc.openid': 'Read the stable identifier for your account.', 'oauth.scopeDesc.profile': 'Read your username, avatar, and basic profile details.', 'oauth.scopeDesc.email': 'Read your email address and its verification status.', 'oauth.scopeDesc.forum.read': 'Read posts and replies you are allowed to view.', 'oauth.scopeDesc.forum.write': 'Create posts and replies and perform related actions as you.', 'oauth.scopeDesc.resource.read': 'Read information about maps, schematics, mods, and other resources.', 'oauth.scopeDesc.resource.download': 'Download public resources using your account.', 'oauth.scopeDesc.resource.upload': 'Submit maps, schematics, mods, and other resources as you.', 'oauth.scopeDesc.notification.read': 'Read notifications sent to your account.', 'oauth.scopeDesc.message.read': 'Read your private messages and conversations.', 'oauth.scopeDesc.message.write': 'Send private messages to other users as you.',
  },
  ru: {
    'oauth.invalidConfiguration': 'У приложения неверно настроен вход. Обратитесь к разработчику.', 'oauth.unavailable': 'Не удалось проверить запрос доступа. Попробуйте позже.', 'oauth.submitFailed': 'Не удалось отправить ваш выбор. Попробуйте позже.', 'oauth.verifying': 'Проверяем запрос доступа…', 'oauth.official': 'Официальное приложение', 'oauth.thirdParty': 'Стороннее приложение', 'oauth.developerBy': 'Разработчик: {name}', 'oauth.officialProvider': 'Предоставлено командой сообщества MindAuth', 'oauth.missingDescription': 'Приложение будет использовать ваш аккаунт MindAuth для безопасного входа и запросит перечисленные права сообщества.', 'oauth.newScopes': 'Приложение запрашивает дополнительные права', 'oauth.requestedScopes': 'Приложение запрашивает следующие права', 'oauth.sensitive': 'Чувствительное разрешение', 'oauth.previousConsent': 'Вы уже разрешили часть прав. Продолжив, вы добавите запрошенные права к доступу приложения.', 'oauth.details': 'Сведения о приложении', 'oauth.clientId': 'Client ID', 'oauth.redirectHost': 'Адрес перенаправления', 'oauth.website': 'Сайт приложения', 'oauth.developer': 'Разработчик', 'oauth.revokeNotice': 'Доступ приложения можно в любое время отозвать в аккаунте MindAuth. Правила сообщества и статус аккаунта продолжают действовать.', 'oauth.cancel': 'Отмена', 'oauth.approve': 'Разрешить', 'oauth.submitting': 'Отправка…', 'oauth.registeredCallback': 'Зарегистрированный адрес перенаправления',
    'oauth.scope.openid': 'Идентификатор аккаунта', 'oauth.scope.profile': 'Основные данные профиля', 'oauth.scope.email': 'Адрес почты', 'oauth.scope.forum.read': 'Просмотр сообщества', 'oauth.scope.forum.write': 'Публикация в сообществе', 'oauth.scope.resource.read': 'Просмотр ресурсов', 'oauth.scope.resource.download': 'Скачивание ресурсов', 'oauth.scope.resource.upload': 'Загрузка ресурсов', 'oauth.scope.notification.read': 'Чтение уведомлений', 'oauth.scope.message.read': 'Чтение личных сообщений', 'oauth.scope.message.write': 'Отправка личных сообщений',
    'oauth.scopeDesc.openid': 'Доступ к постоянному идентификатору аккаунта.', 'oauth.scopeDesc.profile': 'Доступ к имени пользователя, аватару и основным данным профиля.', 'oauth.scopeDesc.email': 'Доступ к адресу почты и статусу подтверждения.', 'oauth.scopeDesc.forum.read': 'Чтение публикаций и ответов, доступных вам.', 'oauth.scopeDesc.forum.write': 'Публикация тем и ответов от вашего имени.', 'oauth.scopeDesc.resource.read': 'Просмотр сведений о картах, схемах, модах и других ресурсах.', 'oauth.scopeDesc.resource.download': 'Скачивание открытых ресурсов через ваш аккаунт.', 'oauth.scopeDesc.resource.upload': 'Публикация карт, схем, модов и других ресурсов от вашего имени.', 'oauth.scopeDesc.notification.read': 'Чтение уведомлений вашего аккаунта.', 'oauth.scopeDesc.message.read': 'Чтение личных сообщений и переписок.', 'oauth.scopeDesc.message.write': 'Отправка личных сообщений другим пользователям от вашего имени.',
  },
  ja: {
    'oauth.invalidConfiguration': 'このアプリのログイン設定に問題があります。開発者にお問い合わせください。', 'oauth.unavailable': 'アクセスリクエストを確認できませんでした。しばらくしてから再試行してください。', 'oauth.submitFailed': '選択内容を送信できませんでした。しばらくしてから再試行してください。', 'oauth.verifying': 'アクセスリクエストを確認中…', 'oauth.official': '公式アプリ', 'oauth.thirdParty': 'サードパーティアプリ', 'oauth.developerBy': '開発者：{name}', 'oauth.officialProvider': 'MindAuth コミュニティチームが提供', 'oauth.missingDescription': 'このアプリは MindAuth アカウントで安全にログインし、申請したコミュニティ権限を利用します。', 'oauth.newScopes': 'このアプリは追加の権限を要求しています', 'oauth.requestedScopes': 'このアプリが要求する権限', 'oauth.sensitive': '慎重な扱いが必要な権限', 'oauth.previousConsent': '一部の権限は許可済みです。続行すると、今回申請された権限が追加されます。', 'oauth.details': 'アプリの詳細', 'oauth.clientId': 'Client ID', 'oauth.redirectHost': 'リダイレクト先', 'oauth.website': 'アプリのサイト', 'oauth.developer': '開発者', 'oauth.revokeNotice': 'アプリのアクセス許可は MindAuth アカウントからいつでも取り消せます。コミュニティのルールとアカウント状態は引き続き適用されます。', 'oauth.cancel': 'キャンセル', 'oauth.approve': '許可', 'oauth.submitting': '送信中…', 'oauth.registeredCallback': '登録済みのリダイレクト URI',
    'oauth.scope.openid': 'アカウント識別子', 'oauth.scope.profile': '基本プロフィール', 'oauth.scope.email': 'メールアドレス', 'oauth.scope.forum.read': 'コミュニティの閲覧', 'oauth.scope.forum.write': 'コミュニティへの投稿', 'oauth.scope.resource.read': 'リソースの閲覧', 'oauth.scope.resource.download': 'リソースのダウンロード', 'oauth.scope.resource.upload': 'リソースのアップロード', 'oauth.scope.notification.read': '通知の閲覧', 'oauth.scope.message.read': 'メッセージの閲覧', 'oauth.scope.message.write': 'メッセージの送信',
    'oauth.scopeDesc.openid': 'アカウントを識別する固定 ID を読み取ります。', 'oauth.scopeDesc.profile': 'ユーザー名、アバターなど基本プロフィールを読み取ります。', 'oauth.scopeDesc.email': 'メールアドレスと確認状態を読み取ります。', 'oauth.scopeDesc.forum.read': '閲覧権限のある投稿と返信を読み取ります。', 'oauth.scopeDesc.forum.write': 'あなたの名前で投稿や返信などを行います。', 'oauth.scopeDesc.resource.read': 'マップ、設計図、Mod などの情報を読み取ります。', 'oauth.scopeDesc.resource.download': 'アカウントを使って公開リソースをダウンロードします。', 'oauth.scopeDesc.resource.upload': 'あなたの名前でマップ、設計図、Mod などを投稿します。', 'oauth.scopeDesc.notification.read': 'アカウント宛ての通知を読み取ります。', 'oauth.scopeDesc.message.read': '個人メッセージと会話を読み取ります。', 'oauth.scopeDesc.message.write': 'あなたの名前で他のユーザーに個人メッセージを送ります。',
  },
} as const;
