import type { Locale } from './catalogs';

const english = {
  'security.title': 'Sign-in and security', 'security.description': 'Manage how you sign in, verify and recover your MindAuth account.', 'security.email': 'Email', 'security.emailDescription': 'Used for sign-in, notifications and account recovery.', 'security.currentEmail': 'Current email', 'security.verified': 'Verified', 'security.unverified': 'Not verified', 'security.sendVerification': 'Send verification email', 'security.changeEmail': 'Change email', 'security.changeEmailDescription': 'We will send a link to your new address. It changes after you verify it.', 'security.newEmail': 'New email', 'security.currentPassword': 'Current password', 'security.sendChangeLink': 'Send change link',
  'security.phone': 'Phone number', 'security.phoneDescription': 'Add a phone number as an optional account recovery method.', 'security.phoneStatus': 'Status', 'security.phoneBound': 'Phone number verified and linked.', 'security.phoneUnbound': 'No phone number linked (optional).', 'security.phoneLabel': 'Phone number', 'security.smsCode': 'SMS code', 'security.resendAfter': 'Resend in {seconds}s', 'security.sendCode': 'Send code', 'security.verifyBind': 'Verify and link',
  'security.password': 'Password', 'security.passwordDescription': 'Update your password regularly and do not reuse it on other services.', 'security.changePassword': 'Change password', 'security.changePasswordDescription': 'Saving will sign out all sessions. You will need to sign in again.', 'security.newPassword': 'New password', 'security.passwordHint': 'At least 8 characters, including uppercase, lowercase and a number', 'security.updatePassword': 'Update password', 'security.social': 'Linked accounts', 'security.socialDescription': 'Use linked accounts to sign in to MindAuth.', 'security.linkedAccount': 'Linked account', 'security.bound': 'Linked', 'security.unbind': 'Unlink', 'security.qqDescription': 'Link QQ to sign in with it later.', 'security.bindQQ': 'Link QQ', 'security.qqBoundToast': 'QQ account linked.',
  'security.dangerTitle': 'Delete account', 'security.dangerDescription': 'Deleting your account permanently removes profile details, authorizations, notifications and sign-in history.', 'security.irreversible': 'This cannot be undone. Your account and associated data cannot be restored.', 'security.deleteAccount': 'Delete account', 'security.confirmUnbind': 'Unlink this account?', 'security.cancel': 'Cancel', 'security.confirmUnbindButton': 'Unlink account', 'security.unbindBody': 'You will no longer be able to sign in with this linked account.', 'security.confirmDelete': 'Delete your account?', 'security.permanentDelete': 'Delete permanently', 'security.deletePrompt': 'Enter your current password to confirm. This action cannot be undone.',
  'security.emailSent': 'Verification email sent.', 'security.emailChangeSent': 'A verification email was sent to your new address. Follow its instructions to finish the change.', 'security.emailChangeFailed': 'Could not start the email change.', 'security.passwordChanged': 'Password updated. Please sign in again.', 'security.passwordChangeFailed': 'Could not change the password.', 'security.emailAndPasswordRequired': 'Enter your new email and current password.', 'security.passwordsRequired': 'Enter your current and new passwords.', 'security.phoneRequired': 'Enter a phone number.', 'security.phoneAndCodeRequired': 'Enter your phone number and verification code.', 'security.codeSent': 'Verification code sent.', 'security.sendCodeFailed': 'Could not send the verification code.', 'security.rateLimited': 'Too many attempts. Try again in {seconds} seconds.', 'security.phoneBoundSuccess': 'Phone number linked.', 'security.phoneVerifyFailed': 'Could not verify the phone number.', 'security.socialUnbound': 'Linked account removed.', 'security.unbindFailed': 'Could not unlink the account.', 'security.deletePasswordRequired': 'Enter your password to confirm deletion.', 'security.accountDeleted': 'Account deleted.', 'security.deleteFailed': 'Could not delete the account.',
};

const russian = {
  'security.title': 'Вход и безопасность', 'security.description': 'Настройте вход, подтверждение и восстановление аккаунта MindAuth.', 'security.email': 'Почта', 'security.emailDescription': 'Используется для входа, уведомлений и восстановления аккаунта.', 'security.currentEmail': 'Текущий адрес', 'security.verified': 'Подтверждена', 'security.unverified': 'Не подтверждена', 'security.sendVerification': 'Отправить письмо для подтверждения', 'security.changeEmail': 'Изменить почту', 'security.changeEmailDescription': 'Мы отправим ссылку на новый адрес. Он изменится после подтверждения.', 'security.newEmail': 'Новый адрес', 'security.currentPassword': 'Текущий пароль', 'security.sendChangeLink': 'Отправить ссылку',
  'security.phone': 'Телефон', 'security.phoneDescription': 'Номер можно добавить для восстановления аккаунта (необязательно).', 'security.phoneStatus': 'Статус', 'security.phoneBound': 'Номер подтверждён и привязан.', 'security.phoneUnbound': 'Номер не привязан (необязательно).', 'security.phoneLabel': 'Номер телефона', 'security.smsCode': 'Код из SMS', 'security.resendAfter': 'Повторить через {seconds} с', 'security.sendCode': 'Отправить код', 'security.verifyBind': 'Подтвердить и привязать',
  'security.password': 'Пароль', 'security.passwordDescription': 'Периодически обновляйте пароль и не используйте его на других сайтах.', 'security.changePassword': 'Сменить пароль', 'security.changePasswordDescription': 'После сохранения завершатся все сеансы, и потребуется войти снова.', 'security.newPassword': 'Новый пароль', 'security.passwordHint': 'Не менее 8 символов, включая заглавные и строчные буквы и цифру', 'security.updatePassword': 'Обновить пароль', 'security.social': 'Связанные аккаунты', 'security.socialDescription': 'Используйте связанные аккаунты для входа в MindAuth.', 'security.linkedAccount': 'Связанный аккаунт', 'security.bound': 'Привязан', 'security.unbind': 'Отвязать', 'security.qqDescription': 'Свяжите QQ, чтобы входить через него.', 'security.bindQQ': 'Связать QQ', 'security.qqBoundToast': 'Аккаунт QQ привязан.',
  'security.dangerTitle': 'Удаление аккаунта', 'security.dangerDescription': 'Профиль, разрешения приложений, уведомления и история входов будут удалены без возможности восстановления.', 'security.irreversible': 'Это действие нельзя отменить. Аккаунт и связанные данные не восстановить.', 'security.deleteAccount': 'Удалить аккаунт', 'security.confirmUnbind': 'Отвязать аккаунт?', 'security.cancel': 'Отмена', 'security.confirmUnbindButton': 'Отвязать', 'security.unbindBody': 'После отвязки вы не сможете входить через этот аккаунт.', 'security.confirmDelete': 'Удалить аккаунт?', 'security.permanentDelete': 'Удалить навсегда', 'security.deletePrompt': 'Введите текущий пароль для подтверждения. Отменить действие нельзя.',
  'security.emailSent': 'Письмо для подтверждения отправлено.', 'security.emailChangeSent': 'На новый адрес отправлено письмо. Следуйте инструкциям, чтобы завершить смену.', 'security.emailChangeFailed': 'Не удалось начать смену почты.', 'security.passwordChanged': 'Пароль обновлён. Войдите снова.', 'security.passwordChangeFailed': 'Не удалось сменить пароль.', 'security.emailAndPasswordRequired': 'Введите новый адрес и текущий пароль.', 'security.passwordsRequired': 'Введите текущий и новый пароль.', 'security.phoneRequired': 'Введите номер телефона.', 'security.phoneAndCodeRequired': 'Введите номер телефона и код подтверждения.', 'security.codeSent': 'Код подтверждения отправлен.', 'security.sendCodeFailed': 'Не удалось отправить код.', 'security.rateLimited': 'Слишком много попыток. Повторите через {seconds} с.', 'security.phoneBoundSuccess': 'Номер телефона привязан.', 'security.phoneVerifyFailed': 'Не удалось подтвердить номер телефона.', 'security.socialUnbound': 'Связанный аккаунт отвязан.', 'security.unbindFailed': 'Не удалось отвязать аккаунт.', 'security.deletePasswordRequired': 'Введите пароль для подтверждения удаления.', 'security.accountDeleted': 'Аккаунт удалён.', 'security.deleteFailed': 'Не удалось удалить аккаунт.',
};

export const securityMessages: Record<Locale, Record<string, string>> = {
  'zh-CN': {}, en: english, ru: russian, ja: {},
};
