export const sharedMessages = {
  'zh-CN': {
    'shell.menuOpen': '打开导航', 'shell.menuClose': '关闭导航', 'shell.brandOverview': 'MindAuth 用户中心概览', 'shell.help': '帮助', 'shell.userMenu': '用户菜单：{username}', 'shell.logout': '退出登录', 'shell.loadingAccount': '正在加载账户', 'shell.sidebar': '账户中心侧栏', 'shell.navigation': '账户中心导航', 'shell.mobileTitle': '账户中心', 'shell.eyebrow': '账户中心', 'shell.home': '返回 MDTBBS', 'shell.homeClub': '返回 Mindustry Club', 'shell.loginRequired': '请先登录后继续。',
    'brand.artAlt': 'Mindustry 方块与传送带组成的社区插图', 'shared.loadingEllipsis': '加载中…', 'shared.clientInfoUnavailable': '客户端信息未提供', 'shared.closeNotification': '关闭通知', 'shared.tableEmpty': '暂无数据', 'shared.refreshTitle': '页面出现了一点问题', 'shared.refreshDescription': '加载时发生了错误。请刷新页面重试；如果问题持续，请联系管理员。', 'shared.refreshAction': '刷新页面',
  },
  en: {
    'shell.menuOpen': 'Open navigation', 'shell.menuClose': 'Close navigation', 'shell.brandOverview': 'MindAuth account overview', 'shell.help': 'Help', 'shell.userMenu': 'User menu: {username}', 'shell.logout': 'Sign out', 'shell.loadingAccount': 'Loading account', 'shell.sidebar': 'Account sidebar', 'shell.navigation': 'Account navigation', 'shell.mobileTitle': 'Account', 'shell.eyebrow': 'Account', 'shell.home': 'Back to MDTBBS', 'shell.homeClub': 'Back to Mindustry Club', 'shell.loginRequired': 'Sign in to continue.',
    'brand.artAlt': 'Community illustration made of Mindustry blocks and conveyors', 'shared.loadingEllipsis': 'Loading…', 'shared.clientInfoUnavailable': 'Client information unavailable', 'shared.closeNotification': 'Dismiss notification', 'shared.tableEmpty': 'No data available', 'shared.refreshTitle': 'Something went wrong', 'shared.refreshDescription': 'An error occurred while loading this page. Refresh and try again. If the problem continues, contact an administrator.', 'shared.refreshAction': 'Refresh page',
  },
  ru: {
    'shell.menuOpen': 'Открыть навигацию', 'shell.menuClose': 'Закрыть навигацию', 'shell.brandOverview': 'Главная аккаунта MindAuth', 'shell.help': 'Помощь', 'shell.userMenu': 'Меню пользователя: {username}', 'shell.logout': 'Выйти', 'shell.loadingAccount': 'Загрузка аккаунта', 'shell.sidebar': 'Боковая панель аккаунта', 'shell.navigation': 'Навигация аккаунта', 'shell.mobileTitle': 'Аккаунт', 'shell.eyebrow': 'Аккаунт', 'shell.home': 'Вернуться на MDTBBS', 'shell.homeClub': 'Вернуться в Mindustry Club', 'shell.loginRequired': 'Войдите, чтобы продолжить.',
    'brand.artAlt': 'Иллюстрация сообщества из блоков и конвейеров Mindustry', 'shared.loadingEllipsis': 'Загрузка…', 'shared.clientInfoUnavailable': 'Сведения о клиенте недоступны', 'shared.closeNotification': 'Закрыть уведомление', 'shared.tableEmpty': 'Нет данных', 'shared.refreshTitle': 'Произошла ошибка', 'shared.refreshDescription': 'При загрузке страницы произошла ошибка. Обновите страницу и попробуйте снова. Если проблема не исчезнет, обратитесь к администратору.', 'shared.refreshAction': 'Обновить страницу',
  },
  ja: {
    'shell.menuOpen': 'ナビゲーションを開く', 'shell.menuClose': 'ナビゲーションを閉じる', 'shell.brandOverview': 'MindAuth アカウントの概要', 'shell.help': 'ヘルプ', 'shell.userMenu': 'ユーザーメニュー：{username}', 'shell.logout': 'ログアウト', 'shell.loadingAccount': 'アカウントを読み込み中', 'shell.sidebar': 'アカウントサイドバー', 'shell.navigation': 'アカウントナビゲーション', 'shell.mobileTitle': 'アカウント', 'shell.eyebrow': 'アカウント', 'shell.home': 'MDTBBS に戻る', 'shell.homeClub': 'Mindustry Club に戻る', 'shell.loginRequired': '続行するにはログインしてください。',
    'brand.artAlt': 'Mindustry のブロックとコンベアで描いたコミュニティのイラスト', 'shared.loadingEllipsis': '読み込み中…', 'shared.clientInfoUnavailable': 'クライアント情報なし', 'shared.closeNotification': '通知を閉じる', 'shared.tableEmpty': 'データがありません', 'shared.refreshTitle': 'エラーが発生しました', 'shared.refreshDescription': 'ページの読み込み中にエラーが発生しました。再読み込みしてください。解決しない場合は管理者にお問い合わせください。', 'shared.refreshAction': 'ページを再読み込み',
  },
} as const;
